In [2]:
import numpy as np

n=5
p=3
X=3.5*np.random.randn(n, p)
print(X)

[[ 4.76298229  6.97668734 -2.37176961]
 [-1.59148381 -1.691931    4.84112239]
 [-6.70836705 -1.39208287  2.30065073]
 [ 4.58903131 -2.55252863 -1.23529772]
 [-0.39963217 -1.8696825  -1.19241825]]


In [47]:
# vediamo questa matrice di cov con le correlazioni come esce
p=10
A = np.random.randn(p, p) #values from standard normal distribution
C = A @ A.T   # positive semidefinite matrix
print(C)
# correlation matrix (Corr)
diag_C = np.sqrt(np.diag(C))
Corr = C / np.outer(diag_C, diag_C)

# check per il numero di valori maggiori di 0.90 e minori di 0.10
print(np.sum(Corr > 0.90))
print(np.sum(Corr < -0.70))

[[ 7.2005915   0.5106835  -3.10952723  2.29637488  0.52249035 -1.95032656
   3.20139406 -2.51269981 -0.8301513   2.37041109]
 [ 0.5106835   8.44481802  3.56617906  4.34507351 -1.43851811  0.19601884
   0.50375004 -5.72755927 -1.30214754  5.38712343]
 [-3.10952723  3.56617906 13.28084053  5.91686708 -2.88921525 -1.97632471
  -2.86792189 -1.57104916  3.50058327 -0.77562063]
 [ 2.29637488  4.34507351  5.91686708 15.26046599 -1.951721    0.7595424
  -3.0837867  -6.13113076 -4.36416577  3.59746102]
 [ 0.52249035 -1.43851811 -2.88921525 -1.951721    4.21973731  1.254561
  -0.90781858  3.44752057  0.05812331  1.54915912]
 [-1.95032656  0.19601884 -1.97632471  0.7595424   1.254561    3.27037698
  -3.23923695  1.11210764 -2.24596519  1.91131861]
 [ 3.20139406  0.50375004 -2.86792189 -3.0837867  -0.90781858 -3.23923695
  11.91015327 -1.04007211  3.05352279 -4.8233261 ]
 [-2.51269981 -5.72755927 -1.57104916 -6.13113076  3.44752057  1.11210764
  -1.04007211  8.05640246  2.42536626 -4.01173493]
 [-

In [10]:
    # mean vector (mu)
p = 5
mu = np.random.randn(p)

    # variances (small range)
variances = np.random.uniform(0.5, 1.5, size=p)
std_devs = np.sqrt(variances)

    # random matrix used to build a valid covariance structure
A = np.random.randn(p, p) #values from standard normal distribution
C = A @ A.T   # positive semidefinite matrix
diag_C = np.sqrt(np.diag(C))
Corr = C / np.outer(diag_C, diag_C)

Sigma = np.outer(std_devs, std_devs) * Corr
X = np.random.multivariate_normal(mu, Sigma, size=n)
print(Sigma)

[[ 1.21922297  0.20001376 -0.34507554  0.42250551  0.36594636]
 [ 0.20001376  1.49154984  0.8068092   0.02036155 -0.58116928]
 [-0.34507554  0.8068092   0.62656056 -0.25274549 -0.41097997]
 [ 0.42250551  0.02036155 -0.25274549  0.84341058 -0.438176  ]
 [ 0.36594636 -0.58116928 -0.41097997 -0.438176    1.16781129]]


In [7]:
import sys
import os

# Add project root to Python path (highest priority)
sys.path.insert(0, os.path.abspath(".."))
print(sys.path)


['/Users/emanuelepasquini/Library/CloudStorage/GoogleDrive-emanuele.pasquini@edu.unifi.it/Il mio Drive/università/MAGISTRALE/superati_anno1/optimization for ml      27/project work OPT/sparse-linear-regression', '/Users/emanuelepasquini/.pyenv/versions/3.12.4/lib/python312.zip', '/Users/emanuelepasquini/.pyenv/versions/3.12.4/lib/python3.12', '/Users/emanuelepasquini/.pyenv/versions/3.12.4/lib/python3.12/lib-dynload', '', '/Users/emanuelepasquini/.pyenv/versions/OPTvenv/lib/python3.12/site-packages']


In [2]:
import numpy as np
from src.least_squares import LeastSquaresProblem

# Create small synthetic problem
n = 5
p = 3

X = np.random.randn(n, p)
beta_true = np.random.randn(p)
y = X @ beta_true

problem = LeastSquaresProblem(X, y)

print("Loss at true beta:", problem.loss(beta_true))

beta_zero = np.zeros(p)
print("Loss at zero beta:", problem.loss(beta_zero))
print("Squared L2 norm of y:", np.linalg.norm(y) ** 2)

Loss at true beta: 0.0
Loss at zero beta: 4.313246024065991
Squared L2 norm of y: 4.313246024065991


In [12]:
problem = LeastSquaresProblem(X, y)

L = problem.lipschitz_constant()
print("L =", L)
# XtX = X.T @ X
# print(XtX)
# #stampa solo gli autovalori in una nuova variabile con la funzione .eig
# eigenvalues = np.linalg.eig(XtX)[0]
# print(eigenvalues)

L = 14.539815339779183


In [4]:
#per capire come funziona argsort e -1 sarebbe l'ulitmo elemento di una lista. quando metti 0:-1 o :-1 prendi tutti tranne the last one
beta = np.array([5.0, -1.0, 0.2, 7.0])
indices = np.argsort(np.abs(beta))
print(indices)
print(indices[0:-1])
print(indices[-1])

[2 1 0 3]
[2 1 0]
3


In [5]:
#per capire come funziona il richiamo di un oggetto che è una classe di funzioni, in iht
import numpy as np
from src.least_squares import LeastSquaresProblem

n = 10
p = 4

beta = np.array([5.0, -1.0, 0.2, 7.0])

X = np.random.randn(n, p)
y = X @ beta

problem = LeastSquaresProblem(X, y)

print(problem.gradient(beta))
print(LeastSquaresProblem(X, y).gradient)

[0. 0. 0. 0.]
<bound method LeastSquaresProblem.gradient of <src.least_squares.LeastSquaresProblem object at 0x105fbf6b0>>


In [6]:
from src.iht import iht
n = 50
p = 100
k = 5

X = np.random.randn(n, p)

beta_true = np.zeros(p)
beta_true[:k] = np.random.randn(k)

#noise = 0.01 * np.random.randn(n)
y = X @ beta_true #+ noise

problem = LeastSquaresProblem(X, y)

beta_hat, history = iht(problem, k)

print("Errore:", np.linalg.norm(beta_hat - beta_true))
print("Numero di non zero stimati:", np.sum(beta_hat != 0))

Errore: 1.0870564272021803
Numero di non zero stimati: 5


In [7]:
# Check Gurobi installation - made 11/03/2026
import gurobipy as gp
print("Gurobi version:", gp.gurobi.version())

Gurobi version: (13, 0, 1)


In [9]:
#test miqp
import numpy as np
from src.least_squares import LeastSquaresProblem
from src.miqp import MIQPSolver

# Dimensioni piccole
n = 20
p = 5
k = 2

np.random.seed(0)

# Genera matrice X
X = np.random.randn(n, p)

# Crea beta vero sparso
beta_true = np.zeros(p)
beta_true[0] = 3.0
beta_true[3] = -2.0

# Genera y senza rumore
y = X @ beta_true

# Crea problema
problem = LeastSquaresProblem(X, y)

# Risolvi con MIQP
solver = MIQPSolver(problem, k)
solver.solve()
beta_miqp = solver.get_solution()

print("Beta true:", beta_true)
print("Beta MIQP:", beta_miqp)
print("Errore:", np.linalg.norm(beta_miqp - beta_true))
print("Numero non zero trovati:", np.sum(np.abs(beta_miqp) > 1e-6))

Set parameter Username
Set parameter LicenseID to value 2790360
Academic license - for non-commercial use only - expires 2027-03-11
Gurobi Optimizer version 13.0.1 build v13.0.1rc0 (mac64[arm] - Darwin 25.3.0 25D2128)

CPU model: Apple M4
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads

Optimize a model with 11 rows, 10 columns and 25 nonzeros (Min)
Model fingerprint: 0xfdbbcdce
Model has 5 linear objective coefficients and an objective constant of 2.8378992878156140e+02
Model has 15 quadratic objective terms
Variable types: 5 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [1e+00, 6e+00]
  Objective range  [2e+01, 1e+02]
  QObjective range [3e+00, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [2e+00, 2e+00]

Found heuristic solution: objective 283.7899288
Presolve time: 0.00s
Presolved: 26 rows, 15 columns, 55 nonzeros
Presolved model has 20 quadratic objective terms
Variable types: 10 continuous, 5 integer (5 bi