In [5]:
import numpy as np

n=5
p=3
X=3.5*np.random.randn(n, p)
print(X)

[[-3.93515788  0.10943091 -1.15586959]
 [ 1.38181641  7.39114219  2.11728479]
 [-2.04277699 -0.33295568 -0.34425682]
 [-5.76513007 -1.51671493  3.95449174]
 [ 0.44602364  1.73348825 -0.48928904]]


In [9]:
# Mean vector (different means)
mu = np.array([0, 2, -1, 0.5])  # length p

# Variances (different for each feature)
variances = np.array([1, 0.5, 0.5, 3])  # length p

# Diagonal covariance matrix
Sigma = np.diag(variances)

# Sample dataset
X = np.random.multivariate_normal(mu, Sigma, size=n)
print(X)
Sigma = np.diag((p, p))
print(Sigma)

[[-2.14427107  2.9095441  -1.49361845 -2.58529407]
 [-0.12485457  0.98124719 -0.16753259  1.31268845]
 [ 1.2034576   1.95069448 -2.42265136  1.85424111]
 [ 0.2335075   1.86175071 -1.78426495 -1.39999763]
 [-0.42443415  1.74646692 -1.35725536  0.44972112]]
[[3 0]
 [0 3]]


In [1]:
import sys
import os

# Add project root to Python path (highest priority)
sys.path.insert(0, os.path.abspath(".."))
print(sys.path)


['/Users/emanuelepasquini/Library/CloudStorage/GoogleDrive-emanuele.pasquini@edu.unifi.it/Il mio Drive/università/MAGISTRALE/superati_anno1/optimization for ml      27/project work OPT/sparse-linear-regression', '/opt/anaconda3/lib/python312.zip', '/opt/anaconda3/lib/python3.12', '/opt/anaconda3/lib/python3.12/lib-dynload', '', '/Users/emanuelepasquini/Library/CloudStorage/GoogleDrive-emanuele.pasquini@edu.unifi.it/Il mio Drive/università/MAGISTRALE/superati_anno1/optimization for ml      27/project work OPT/sparse-linear-regression/OPTvenv/lib/python3.12/site-packages']


In [2]:
import numpy as np
from src.least_squares import LeastSquaresProblem

# Create small synthetic problem
n = 5
p = 3

X = np.random.randn(n, p)
beta_true = np.random.randn(p)
y = X @ beta_true

problem = LeastSquaresProblem(X, y)

print("Loss at true beta:", problem.loss(beta_true))

beta_zero = np.zeros(p)
print("Loss at zero beta:", problem.loss(beta_zero))
print("Squared L2 norm of y:", np.linalg.norm(y) ** 2)

Loss at true beta: 0.0
Loss at zero beta: 4.313246024065991
Squared L2 norm of y: 4.313246024065991


In [12]:
problem = LeastSquaresProblem(X, y)

L = problem.lipschitz_constant()
print("L =", L)
# XtX = X.T @ X
# print(XtX)
# #stampa solo gli autovalori in una nuova variabile con la funzione .eig
# eigenvalues = np.linalg.eig(XtX)[0]
# print(eigenvalues)

L = 14.539815339779183


In [4]:
#per capire come funziona argsort e -1 sarebbe l'ulitmo elemento di una lista. quando metti 0:-1 o :-1 prendi tutti tranne the last one
beta = np.array([5.0, -1.0, 0.2, 7.0])
indices = np.argsort(np.abs(beta))
print(indices)
print(indices[0:-1])
print(indices[-1])

[2 1 0 3]
[2 1 0]
3


In [5]:
#per capire come funziona il richiamo di un oggetto che è una classe di funzioni, in iht
import numpy as np
from src.least_squares import LeastSquaresProblem

n = 10
p = 4

beta = np.array([5.0, -1.0, 0.2, 7.0])

X = np.random.randn(n, p)
y = X @ beta

problem = LeastSquaresProblem(X, y)

print(problem.gradient(beta))
print(LeastSquaresProblem(X, y).gradient)

[0. 0. 0. 0.]
<bound method LeastSquaresProblem.gradient of <src.least_squares.LeastSquaresProblem object at 0x105fbf6b0>>


In [6]:
from src.iht import iht
n = 50
p = 100
k = 5

X = np.random.randn(n, p)

beta_true = np.zeros(p)
beta_true[:k] = np.random.randn(k)

#noise = 0.01 * np.random.randn(n)
y = X @ beta_true #+ noise

problem = LeastSquaresProblem(X, y)

beta_hat, history = iht(problem, k)

print("Errore:", np.linalg.norm(beta_hat - beta_true))
print("Numero di non zero stimati:", np.sum(beta_hat != 0))

Errore: 1.0870564272021803
Numero di non zero stimati: 5


In [7]:
# Check Gurobi installation - made 11/03/2026
import gurobipy as gp
print("Gurobi version:", gp.gurobi.version())

Gurobi version: (13, 0, 1)


In [9]:
#test miqp
import numpy as np
from src.least_squares import LeastSquaresProblem
from src.miqp import MIQPSolver

# Dimensioni piccole
n = 20
p = 5
k = 2

np.random.seed(0)

# Genera matrice X
X = np.random.randn(n, p)

# Crea beta vero sparso
beta_true = np.zeros(p)
beta_true[0] = 3.0
beta_true[3] = -2.0

# Genera y senza rumore
y = X @ beta_true

# Crea problema
problem = LeastSquaresProblem(X, y)

# Risolvi con MIQP
solver = MIQPSolver(problem, k)
solver.solve()
beta_miqp = solver.get_solution()

print("Beta true:", beta_true)
print("Beta MIQP:", beta_miqp)
print("Errore:", np.linalg.norm(beta_miqp - beta_true))
print("Numero non zero trovati:", np.sum(np.abs(beta_miqp) > 1e-6))

Set parameter Username
Set parameter LicenseID to value 2790360
Academic license - for non-commercial use only - expires 2027-03-11
Gurobi Optimizer version 13.0.1 build v13.0.1rc0 (mac64[arm] - Darwin 25.3.0 25D2128)

CPU model: Apple M4
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads

Optimize a model with 11 rows, 10 columns and 25 nonzeros (Min)
Model fingerprint: 0xfdbbcdce
Model has 5 linear objective coefficients and an objective constant of 2.8378992878156140e+02
Model has 15 quadratic objective terms
Variable types: 5 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [1e+00, 6e+00]
  Objective range  [2e+01, 1e+02]
  QObjective range [3e+00, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [2e+00, 2e+00]

Found heuristic solution: objective 283.7899288
Presolve time: 0.00s
Presolved: 26 rows, 15 columns, 55 nonzeros
Presolved model has 20 quadratic objective terms
Variable types: 10 continuous, 5 integer (5 bi